### ISSUE TITLE
Wheel dependency

### ISSUE THREAD

**Issue by m-kus** [baking-bad/pytezos#133]
`error: invalid command 'bdist_wheel'` if `wheel` package is absent in the target environment

**Comment by niklr** [comment]
how did you solve this? when I try to install pytezos 3.2.6 it fails with: `error: invalid command 'bdist_wheel'`

and `ERROR: No matching distribution found for secp256k1==0.13.2`

**Comment by niklr** [comment]
https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci

This worked but after pip install wheel I had to pip uninstall -r requirements.txt and redo pip install -r requirements.txt

**Comment by m-kus** [comment]
Try to `pip install wheel` to resolve the first one and `sudo apt install libsecp256k1 for the second
