### ISSUE TITLE
Encrypted key: try to read passphrase from an env variable

### ISSUE THREAD

**Issue by m-kus** [baking-bad/pytezos#178]

**Comment by droserasprout** [comment]
Is it about `deploy` cli command? Which variable name would fit better, `PYTEZOS_SECRET_KEY` for example?

**Comment by m-kus** [comment]
Sorry, meaning this method: https://github.com/baking-bad/pytezos/blob/818c5a2fedc6cc9875ca789f7de265178b57eaf6/pytezos/crypto/key.py#L135

One need to refactor this place so that:
- passphrase is none by default (empty string should be considered a specified value)
- if passphrase is none, try to read os.environ['PYTEZOS_PASSPHRASE']
