### ISSUE TITLE
inject: introduce min_confirmations parameter

### ISSUE THREAD

**Issue by m-kus** [baking-bad/pytezos#185]
By default inject with _async=False waits for a single confirmation (inclusion).
Add an ability to specify how many confirmations user would like to wait for.

ALSO, we can now eliminate _async key (_async=True case is covered by `min_confirmations=0`). Need to mark it as deprecated.

**Comment by jpic** [comment]
Shouldn't this feature have tests and documentation?

Regression in 3.4.2? #295 
No mention in docs? $ grep -r min_conf
