### ISSUE TITLE
activate_account fail when autofill

### ISSUE THREAD

**Issue by multisme** [baking-bad/pytezos#202]
Hi
If one use autofill on the activate_account operation, the function fill_content fills the contents of the operation with None:

This happens because this condition is not fufilled:
https://github.com/baking-bad/pytezos/blob/master/src/pytezos/operation/group.py#L227

because of this:
https://github.com/baking-bad/pytezos/blob/master/src/pytezos/operation/group.py#L26

Cordially,

Multisme

**Comment by multisme** [comment]
I made a pull request here in case of:
https://github.com/baking-bad/pytezos/pull/203/commits

**Comment by m-kus** [comment]
resolved in #170 
will be included in 3.1.0
