### ISSUE TITLE
Split requirements

### ISSUE THREAD

**Issue by jpic** [baking-bad/pytezos#227]
It turns out the whole Tezos VM is useful on its own, ie. it's used by [pymich](https://yourlabs.io/piratzlabs/pymich) to transpile pure Python into Michelson.

As such, pytezos is listed as a pip dependency, which then pulls out all the heavy dependencies of pytezos such as secp256k1 and so on, which might as well not be necessary at all.

Would it be possible to move heavy dependencies used to interact with the actual blockchain in an extra_require? This would all `pip install pytezos` to pull only pure python dependencies, and `pip install pytezos[blockchain]` or something like that to pull secp256k1 and other dependencies which are not necessary to run the PyTezos Tezos VM.

**Comment by m-kus** [comment]
But Tezos VM also depends on crypto primitives :)
Anyways, I tried that some time ago and it added unnecessary friction for user so I decided to revert that change.
Ideally, there should be opt-out mechanism in pip, you can actually achieve something close by installing pytezos with `--no-deps` and then selectively installing its dependencies
