### ISSUE TITLE
Parse raw signed / unsigned transaction

### ISSUE THREAD

**Issue by datgrog** [baking-bad/pytezos#231]
Is it possible to parse raw signed / unsigned transaction ?

**Comment by m-kus** [comment]
There's no way to do that without an RPC call at the moment

**Comment by datgrog** [comment]
Many thanks.
Do you know what call is that ? I try to play with some endpoint but no result passing "binary payload" as described in the doc... Also, Is it possible to use pytezos to inject raw signed transaction ?

**Comment by m-kus** [comment]
Here's the endpoint https://tezos.gitlab.io/009/rpc.html#post-block-id-helpers-parse-operations

Sure, you can: https://github.com/baking-bad/pytezos/blob/b4af4fb54798718bda7ae66af7f67e69103b19ac/src/pytezos/operation/group.py#L347

**Comment by datgrog** [comment]
Many thanks for your quick reply 👍
