### ISSUE TITLE
"assert False" should never happen in production code 

### ISSUE THREAD

**Issue by dani-jozsef** [baking-bad/pytezos#243]
It's been a major issue for us trying to use PyTezos in production - you can't catch assertions, and "assert False" says little about what the error really is. Would it be possible to replace these with normal error behavior, probably providing legible information about what went wrong?

**Comment by m-kus** [comment]
You can catch AssertionError, but it is not a good pattern indeed.
We are gradually replacing asserts with meaningful errors and eventually will get rid of them.
What was your case when you got assert false?

**Comment by dani-jozsef** [comment]
I was trying to inject and wait for an operation group hash on Flextesa. I'm unsure what exactly happened.

**Comment by m-kus** [comment]
Please try 3.2.7
In case it's still can be reproduced I would need some context

**Comment by dani-jozsef** [comment]
We tried to reproduce even on older versions but it seemed quite intermittent. If it comes up again I'll reopen the ticket with more details.

**Comment by m-kus** [comment]
Sure, thanks!
