### ISSUE TITLE
PyTezosClient.wait doesn't actually wait

### ISSUE THREAD

**Issue by owen9825** [baking-bad/pytezos#246]
Upon creating a `PyTezosClient` pointed at a local sandbox, if I call `my_client.wait(num_blocks_wait=1)`, no waiting actually occurs; and the block remains the same, before and after:

```python
def verbose_wait():
    print(my_client.shell.head.hash())
    my_client.wait(num_blocks_wait=1)
    print(my_client.shell.head.hash())
```

```text
BLf1jwWKv8GxZ2fwUbVjmyGJeLynaPM3fvQhMAsT6d6rsntPhuM
BLf1jwWKv8GxZ2fwUbVjmyGJeLynaPM3fvQhMAsT6d6rsntPhuM
```

The expected behaviour here is that with `1` block to wait, the hash would have incremented. It wasn't quite clear to me how best to implement this; and I noticed some confounding complications:

- `PyTezosClient.wait()` accepts `num_blocks_wait`, a number of blocks, but then this is passed as `ttl`, which is documented in `wait_operations` as `max time-to-live` in the mempool. It has therefore dropped its meaning as a strict number of blocks; and become merely an upper bound.
- `wait_blocks()` accepts a flag `yield_curent=True` − it's not clear to me why this is happening. If the function is meant to be ineffective, why call it in the first place? Just personal preference, I guess.

`wait_next_block` sounded perfect, but has been marked as deprecated. I see that it's reverse-engineering the average time between blocks − is there a way to extract this more definitively?

**Comment by m-kus** [comment]
`PyTezosClient.wait` is roughly `await Promise.all` e.g. it waits until all the operations passed have enough confirmations. Here's an example with sandbox: https://github.com/baking-bad/pytezos/blob/c05a013fe25cbd8b073b0d5acff3009ed8dad90e/tests/sandbox_tests/test_concurrent.py#L55

In order to just wait for the next block you can use `PyTezosClient.shell.wait_blocks`. Here is how it's used internally for awaiting confirmations: https://github.com/baking-bad/pytezos/blob/c05a013fe25cbd8b073b0d5acff3009ed8dad90e/src/pytezos/rpc/shell.py#L149

**Comment by owen9825** [comment]
Yes, I saw that `wait()` calls `wait_blocks()`, but the end result is still that the block hash is the same. I had wanted to check a client's balance, call a contract, then see that the client's balance has decremented from gas fees, but the balance was in fact remaining the same, presumably because the block hash was still the same.

Anyway, I don't believe that `wait()` is fulfilling its advertised properties. Perhaps it's documentation that needs to change as opposed to functionality, but I can't really agree that it's working fine as-is :/

Ideally, alongside the deprecation notice of `wait_next_block()`, there could be a note about how else the result could be achieved :)

**Comment by m-kus** [comment]
`wait()` explicitly says that it waits for multiple injected operations get enough confirmations, but you are right that there should be a check for empty operation list arg.

I've added `PyTezosClient.sleep()` helper that does what you initially wanted (will be in 3.2.7).
