### ISSUE TITLE
Arm Support [Raspberry pi]

### ISSUE THREAD

**Issue by vivekascoder** [baking-bad/pytezos#250]
Is this library compatible with ARM architecture, specifically with raspberrypi ?

**Comment by vivekascoder** [comment]
I am facing issues while installing it.
![image](https://user-images.githubusercontent.com/54495208/129933841-f96d44c6-737d-4f31-8f0a-21ebea07ee37.png)

**Comment by m-kus** [comment]
Try to do `pip install wheel setuptools` and then another attempt to install pytezos

**Comment by m-kus** [comment]
Closing for now (it works ok on M1), feel free to reopen if it's still the case
