### ISSUE TITLE
Unexpected return types when calling Interpreter.run_view

### ISSUE THREAD

**Issue by dorranh** [baking-bad/pytezos#251]
While working with checker's off-chain views using pytezos, we noticed that the objects we were getting back when calling `storage_view()` didn't include the expected record field names despite them being specified in the view metadata ([example](https://github.com/tezos-checker/checker/blob/335029d7f28e0338e754d1fa26722f321770f8d2/e2e/main.py#L610)). In other cases I've also found that the "python object" you get back from `storage_view()` isn't always a `dict` even though the returned pair has name annotations.

I looked into this today and will follow up this issue with a corresponding PR.

**Comment by m-kus** [comment]
Thanks again!
In 3.2.10

**Comment by dorranh** [comment]
No problem! :slightly_smiling_face:
