### ISSUE TITLE
Regression in offline view behavior for storage with bigmaps

### ISSUE THREAD

**Issue by dorranh** [baking-bad/pytezos#269]
Earlier this year, we ran into an issue where calling `contract.metadata.someView.storage_view()` for contracts with a bigmap in their storage returned empty results despite there actually being data in the contract's bigmap (https://github.com/baking-bad/pytezos/issues/233). This was fixed in https://github.com/baking-bad/pytezos/pull/234 and has been working well for us the past few months.

I recently went to upgrade `checker` to use the latest version of pytezos (`3.1.1`) and noticed a regression to the behavior identified in (https://github.com/baking-bad/pytezos/issues/233). I am not 100% sure, but I think* that this is regression happened in #265 where it appears to have [removed part of the solution](https://github.com/baking-bad/pytezos/commit/c51282a19c9787583f9363b338c0b6d8325fb455#diff-7f012660efd2609ccf17bd2e5f722b788489a76e1a07ef2a9aa485805db2c2bdL261-L276) added in the earlier fix.

Would you all be able to take a look at this? Checker has several bigmaps in its storage, so this issue is unfortunately blocking us from upgrading to a newer version of pytezos. 

Thanks!

**Comment by m-kus** [comment]
Is there any mainnet/kaizen deployment (permanent) I can use for a regression test?
I have only the one in the florencenet :(

**Comment by dorranh** [comment]
Thanks, @m-kus!
