### ISSUE TITLE
Stale contract storage passed to ContractViewCall.storage_view

### ISSUE THREAD

**Issue by dorranh** [baking-bad/pytezos#271]
Hey, it's me again :smile:

Following the patch for #269 (#270), we are now able to call storage views which access contract storage fields of type `bigmap`. However, it seems that the contract storage passed to `storage_view()` is not always up to date with the actual current state of the contract.

For example, consider the following sequence of steps:

1. Contract originated. `ContractInterface` created by calling `my_contract = pytezos_client.contract(new_contract_address)`
2. Entrypoints called which update contract state: `my_contract.someEntrypoint().autofill().sign().inject()`
3. Storage view called: `my_contract.metadata.someStorageView.storage_view()`

When the storage view is called at step 3, the view operates on the contract storage seemingly from when `my_contract` was instantiated at step 1 and not on the latest state of the contract.

**Comment by ztepler** [comment]
Hi, I faced this problem too and I was able to reproduce this in sandbox test. Maybe this would help somehow:
```python
from pytezos.sandbox.node import SandboxedNodeTestCase
from pytezos import ContractInterface


# This contract updates his storage with number provided to default and allow
# to view this number using getValue view:
code = """
{
    parameter nat ;
    storage nat ;
    code { CAR ; NIL operation ; PAIR } ;
    view "getValue" unit nat { CDR }
}
"""


class ViewTestCase(SandboxedNodeTestCase):
    def originate_contract(self, storage):
        ci = ContractInterface.from_michelson(code).using(
            shell=self.client.shell,
            key=self.client.key
        )
        res = ci.originate(initial_storage=storage).send()
        self.bake_block()

        op = self.client.shell.blocks['head':].find_operation(res.hash())
        op_result = op['contents'][0]['metadata']['operation_result']
        address = op_result['originated_contracts'][0]
        contract = self.client.contract(address)
        return contract

    def test_check_view_should_be_updated(self):

        # originating contract with value 12:
        contract = self.originate_contract(12)
        self.assertEqual(contract.getValue().storage_view(), 12)

        # updating value to 33:
        contract.default(33).send()
        self.bake_block()
        self.assertEqual(contract.getValue().storage_view(), 33)
```
