### ISSUE TITLE
Michelson interpreter error ('EXEC', 'expected nat, got address at `/0/0`')

### ISSUE THREAD

**Issue by konchunas** [baking-bad/pytezos#272]
Pytezos 3.3.2

Michelson interpreter failing with the following error:
```
args = (<class 'pytezos.michelson.micheline.MichelineSequence'>, [<-1>, tz1iA1…saW, Lambda], ['BEGIN %default / _ => (tz1iBo…...0) => tz1iBo…LCX', 'EMPTY_BIG_MAP / _ => <-1>', ...], <pytezos.context.impl.ExecutionContext object at 0x7ff17e355250>)

...

pytezos.michelson.micheline.MichelsonRuntimeError: ('EXEC', 'expected nat, got address at `/0/0`')
```

This happens when Ligo function in original code is used more than once, so it is not inlined. And it seems to be related to passing a result of container access directly to the function, like so: `unwrap_or(container[key], 0n);`
Issue can be reproduced this with both older Ligo versions and Pytezos versions, though I can't understand why didn't this happen earlier

I have isolated minimal reproducible example here: https://github.com/konchunas/pytezos-exec-error-sample

Any help is appreciated

**Comment by m-kus** [comment]
Thank you for the test case!
It was a very stupid typo, when `GET` returned `None` it was constructed with the key type instead of the value type. So instead of `option nat` it expected `option address`
