### ISSUE TITLE
How to install in editable mode

### ISSUE THREAD

**Issue by jpic** [baking-bad/pytezos#277]
Hi!

Trying to install the app in editable mode, as usual, to fix a bug in my use case and contribute, but:

```
22/12 2021 11:44:25 jpic@jpic ~/src/pytezos  (master)
$ pip install --user -e .
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/jpic/src/pytezos
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

Anyone can share a way to install this module in editable mode please?

Thanks! :tophat:

**Comment by m-kus** [comment]
They say it should be available soon: https://github.com/python-poetry/poetry/issues/34#issuecomment-947773710

I tried to update pip and install poetry-core from master, but didn't work for me🤷‍♂️

**Comment by m-kus** [comment]
I will close this issue for now, feel free to reopen if neither of the following options suits your needs:
* poetry + pycharm https://www.jetbrains.com/help/pycharm/poetry.html
* poetry + vscode https://www.pythoncheatsheet.org/blog/python-projects-with-poetry-and-vscode-part-1/
* poetry + jupyter https://hippocampus-garden.com/jupyter_poetry_pipenv/

**Comment by jpic** [comment]
I use vim but it's okay I'll just add a setup.py in my wc

**Comment by m-kus** [comment]
You can start vim from the poetry shell
