### ISSUE TITLE
Consider splitting pytezos.crypto into a separate pip package

### ISSUE THREAD

**Issue by elric1** [baking-bad/pytezos#284]
The smaller package would be of use in at least two projects with which I am involved to reduce the size of our generated docker images.

**Comment by aliel** [comment]
Up

**Comment by hoh** [comment]
Installing Pytezos currently requires approximately 141 MB of dependencies, including Jupyter and other libraries that are not useful for checking signature and other cryptographic operations.

**Comment by elric1** [comment]
For my purposes, `pytezos.crypto` is sufficient.

**Comment by hoh** [comment]
`pytezos.crypto` would also be sufficient for my usecases.

**Comment by aliel** [comment]
Hello, we forked the crypto part available here => https://github.com/aleph-im/aleph-pytezos

**Comment by droserasprout** [comment]
@aliel, @elric1, could you please try the following image:

```shell
$ docker pull ghcr.io/baking-bad/pytezos-core:aux-initial-release
```

Does everything work as expected?

**Comment by droserasprout** [comment]
After some consideration we decided that maintaining a separate package would be too time consuming despite being technically possible. Our latest Docker image is 122MB uncompressed, which isn't perfect, but, well, competitive I think. Closing this issue as wontdo.

Please, don't use `pytezos-core 1.0.0rc1` prerelease image and Python package as they are very outdated.
