### ISSUE TITLE
cannot import name 'NonFungibleTokenImpl' from 'pytezos' 

### ISSUE THREAD

**Issue by denizhankara** [baking-bad/pytezos#286]
The NonFungibleTokenImpl interface in pytezos is missing/not available. 

I would like to use it for implementing NFT operations in Tezos Blockchain, as per the repository here:
https://github.com/baking-bad/tezos-nft-sample/blob/master/client.py

Could you help regarding where this interface is provided, or how to implement a similar NFT interface with NonFungibleTokenImpl using pytezos?

Thanks.

**Comment by Yuxanju** [comment]
You will have to synchronize your wallet and then you debug it with bech13

**Comment by m-kus** [comment]
Hey @denizhankara , you actually don't need NonFungibleTokenImpl, just use

```
from pytezos import ContractInterface

app = ContractInterface.from_file(...)
```

In order to see the method signatures do:

```
print(app)
```

and then for each entrypoint:

```
print(app.<entrypoint>)
```

**Comment by denizhankara** [comment]
Confirmed that we can use the `ContractInterface` method in the current pytezos function to see and interact with contract method signatures, as @m-kus suggested.

Thanks a lot for the help!
