### ISSUE TITLE
Build pytezos

### ISSUE THREAD

**Issue by louptheron** [baking-bad/pytezos#30]
Hi, we would like to use pytezos as a module without waiting for releases in order to get the latest version, could you add the steps in order to achieve that ?

Thank you very much,
Loup

**Comment by m-kus** [comment]
Hi! Sorry for the delay :(
You can install from a specific branch:
```
pip install git+https://github.com/baking-bad/pytezos.git@feature/babylon
```

**Comment by louptheron** [comment]
Thank you!
