### ISSUE TITLE
Autofill fails with `proto.012-Psithaca.gas_exhausted.block` when sending a batch

### ISSUE THREAD

**Issue by m-kus** [baking-bad/pytezos#305]
Originally submitted by chas#7053

Steps to reproduce:
https://colab.research.google.com/drive/11wy8RfCzmlbjNLdN5G00tpZKN-X3yQvK?usp=sharing

Error meaning:
`proto.012-Psithaca.gas_exhausted.block` means that the total gas limit is greater than the hard cap per block.

Problem:
`autofill` sets transaction gas_limit to max possible value per operation and in the batch scenario the sum can be too large.

Possible solution:
It's not necessary to specify fees/limits in every operation in a batch, it is sufficient to just set those fields (fee, gas_limit, storage_limit) for the first one.

**Comment by chasdabigone** [comment]
I think each transaction still needs `storage_limit` and `gas_limit`. Only `fee` should be restricted to the first. See difference between these opgs:

https://better-call.dev/mainnet/opg/opWdgQBS1umdwJjaC9JkXzJ31sA7hGyZPccdnq9hkdAwLwxovZ9/contents (baker fee only in first)

https://better-call.dev/mainnet/opg/op5BFGcTEkxB7V1JXmixpecNMZgm5J7GkSZkHf8u85axWU2winF/contents (built by pytezos - baker fee in both transactions)
