### ISSUE TITLE
How to bytepack nested pairs

### ISSUE THREAD

**Issue by tbinetruy** [baking-bad/pytezos#312]
Currently, it seems like `pytezos.michelson.micheline.PairType.pack` does not byte-pack like a tezos node would for nested pairs. 

Example:

```python
from pytezos.michelson.types import MichelsonType
from pytezos.michelson.parse import michelson_to_micheline

message_format = '(pair nat (pair nat (pair nat nat)))'
ty = MichelsonType.match(michelson_to_micheline(message_format))
micheline = michelson_to_micheline('(Pair 1 (Pair 2 (Pair 3 4)))')
message = ty.from_micheline_value(micheline).pack()
message.hex()  # 0x0502000000080001000200030004
```

Using the `tezos-client` however, we get a different value:

```sh
tezos-client hash data '(Pair 1 (Pair 2 (Pair 3 4)))' of type '(pair nat (pair nat (pair nat nat)))'

# Raw packed data: 0x050707000107070002070700030004
```
And indeed, the `tezos-client` cli byte-unpacks the pytezos result as a sequence:

```sh
tezos-client unpack michelson data "0x0502000000080001000200030004"
# { 1 ; 2 ; 3 ; 4 }
```

Whereas it does byte-unpack its result as the expected nested pair:

```sh
tezos-client unpack michelson data "0x050707000107070002070700030004"
Pair 1 (Pair 2 (Pair 3 4))
```

Unfortunately this proves to be problematic when wanting to verify on-chain data that was signed on a Pytezos byte-pack output.

Is there anyway to get the output that `tezos-client` gives when byte-packing nested pairs using Pytezos? If not, how can I help contributing with a fix? The codebase for the byte-packing looks quite tough :)

Thanks!

P.S. As a side note, byte packing a pair does result in the same output between Pytezos and the Tezos CLI:

```python
message_format = '(pair nat nat)'
ty = MichelsonType.match(michelson_to_micheline(message_format))
micheline = michelson_to_micheline('(Pair 3 4)')
message = ty.from_micheline_value(micheline).pack()
message.hex()  # 0x05070700030004
```

And:

```sh
tezos-client hash data '(Pair 3 4)' of type '(pair nat nat)'
# Raw packed data: 0x05070700030004
```

**Comment by m-kus** [comment]
Hey!

You need to pass additional flag:

```
.pack(legacy=True)
```

This is from the times before combs, tezos-client does packing with backward compatibility so that things like e.g. big map key hashes remain the same.

**Comment by tbinetruy** [comment]
Ah niiice, thank you so much :)
