### ISSUE TITLE
Error : pytezos.rpc.node.RpcError: ('Json_encoding.Unexpected_field("entrypoint")',)

### ISSUE THREAD

**Issue by vnea** [baking-bad/pytezos#32]
Hello,

I have a simple SmartContract in Michelson with two entrypoints : mul_a_b and mul_c_d.

```
parameter (or (pair %mul_a_b (int %a) (int %b)) (pair %mul_c_d (int %c) (int %d))) ;
storage int ;
code { DUP ;
       CDR ;
       SWAP ;
       CAR ;
       IF_LEFT
         { PAIR ; DUP ; DUP ; CAR; CDR ; SWAP ; CAR; CAR ; MUL ; SWAP ; DROP }
         { PAIR ; DUP ; DUP ; CAR; CDR ; SWAP ; CAR; CAR ; MUL ; SWAP ; DROP } ;
       NIL operation ;
       PAIR }
```

Then, I defined a simple test : 
```python
from os.path import dirname, join
from unittest import TestCase

from pytezos import ContractInterface, MichelsonRuntimeError

project_dir = dirname(dirname(__file__))

class HelloWorldContractTest(TestCase):

    @classmethod
    def setUpClass(cls):
        cls.helloWorld = ContractInterface.create_from(join(project_dir, 'src/helloWorldCode.tz'), shell='sandboxnet')

    def test_mul_a_b(self):
        res = self.helloWorld \
            .mul_a_b(a=2, b=3) \
            .result(storage=0)

        self.assertEqual(6, res.storage)
```
So, It was working fine with pytezos-2.0.8 but I upgraded to pytezos-2.1.0 but now I have the error `pytezos.rpc.node.RpcError: ('Json_encoding.Unexpected_field("entrypoint")',)`  when I run the test :
![image](https://user-images.githubusercontent.com/10775422/67672288-e894c880-f977-11e9-9f17-41588fe90b83.png)

What should I do ?

**Comment by m-kus** [comment]
Hello, Sorry for delay! I guess that's because your sandbox node is running Athens protocol, but new Pytezos version is adapted for Babylon. Unfortunately, there will be no back compatibility in terms of interacting with contracts in order to keep the code clean.  
You can either:
1) use the previous version:
```
pip install 'pytezos==2.0.8' --force-reinstall
```
2) use default public node
```
cls.helloWorld = ContractInterface.create_from(join(project_dir, 'src/helloWorldCode.tz'))
```
3) or upgrade your sandbox node

**Comment by vnea** [comment]
I upgraded pytezos to pytezos-2.1.2 and I used solution 2.
It worked, thank you.
