### ISSUE TITLE
MichelineSchemaError when running test

### ISSUE THREAD

**Issue by vnea** [baking-bad/pytezos#33]
Hello,

By using SmartPy, I wrote this simple Smart Contract with one storage containing a pair of address and string :
```python
import smartpy as sp

class ComplexStorage(sp.Contract):
    """
        ownerAddress : address
        name : string
    """
    def __init__(self, ownerAddress, name):
        self.init(ownerAddress=ownerAddress, name=name)

    @sp.entryPoint
    def set_name(self, name):
        self.data.name = name
```

Then I compiled it into Michelson using SmartPy CLI :
```michelson
parameter string ;
storage (pair (string %name) (address %ownerAddress)) ;
code { DUP ;
            DUP ;
            CDR ;
            SWAP ;
            CAR ;
            SWAP ;
            CDR ;
            SWAP ;
            PAIR ;
            SWAP ;
            DROP ;
            NIL operation ;
            PAIR }
```

And then this related test :
```python
from os.path import dirname, join
from unittest import TestCase

from pytezos import ContractInterface, MichelsonRuntimeError

project_dir = dirname(dirname(__file__))

class ComplexStorageContractTest(TestCase):

    @classmethod
    def setUpClass(cls):
        cls.complexStorage = ContractInterface.create_from(join(project_dir, 'src/complexStorageCode.tz'), shell='sandboxnet')

    def test_set_name(self):
        res = self.complexStorage.call("newName")
        res.result(storage=['name', 'tz1YQTmJxey1qR9xD49V9eVmqgJ6DdcBPDyY'])
        # self.assertEqual(..., res.storage)
```

But the test fails with a `pytezos.michelson.converter.MichelineSchemaError` error because the line `res.result(storage=['name', 'tz1YQTmJxey1qR9xD49V9eVmqgJ6DdcBPDyY'])` seems to be incorrect :
![image](https://user-images.githubusercontent.com/10775422/67695805-024d0480-f9a6-11e9-85b0-990f206d45ef.png)

I am using **pytezos-2.0.8**.

**Comment by m-kus** [comment]
Since your storage type is well annotated, something like the following is expected (it's contained in the error output):
```
storage={
	'name': 'name',
    'owner_address': 'tz1YQTmJxey1qR9xD49V9eVmqgJ6DdcBPDyY'
}
```

**Comment by vnea** [comment]
Thank you it worked.

Now, I upgraded pytezos version to **pytezos-2.1.2** in order to be compliant with Babylon protocol.
I updated the code like this :
```python
from os.path import dirname, join
from unittest import TestCase

from pytezos import ContractInterface, MichelsonRuntimeError

project_dir = dirname(dirname(__file__))

class ComplexStorageContractTest(TestCase):

    @classmethod
    def setUpClass(cls):
        cls.complexStorage = ContractInterface.create_from(join(project_dir, "src/complexStorageCode.tz")) # Now I use your Babylon node

    def test_set_name(self):
        res = self.complexStorage.call("new_name")
        res.result(storage={"name": "init_name", "ownerAddress": "tz1YQTmJxey1qR9xD49V9eVmqgJ6DdcBPDyY"})
        # self.assertEqual(..., res.storage)

```

But now I have this error :
![image](https://user-images.githubusercontent.com/10775422/68145184-874f9500-ff35-11e9-8c68-0bf1c5ce011a.png)

It seems like it tries to call the **root** entrypoint but I don't have any entrypoints in this sample.

**Comment by m-kus** [comment]
That's a bug indeed, will fix asap

**Comment by vnea** [comment]
Okay thank you.

1. Do you have a channel like Slack, Telegram, ... where we can directly ask you questions ?
2. When the shell parameter is not specidifed, it uses your default babylon node. So when I run the test, is our contract deployed on your node to run the execution when I call an entrypoint ?

**Comment by m-kus** [comment]
You can write to https://t.me/baking_bad_chat or to me directly @m_kus
Nope, `run_code/trace_code` does not deploy a contract, just instantiates Michelson interpreter.
