### ISSUE TITLE
Signature for p2 may be shorter than 64 bytes, then base58 fails

### ISSUE THREAD

**Issue by dimaa6** [baking-bad/pytezos#47]
int_to_bytes encodes integer to bytes. sign method of Key class in crypto.py concatenates int_to_bytes(r) and int_to_bytes(s). If integer fits into less than 32 bytes, int_to_bytes returns less than 32 bytes, and signature becomes shorter than 64 bytes. Then base58 encoding fails as lengths don't match. You need to left-pad anything returned from int_to_bytes which is shorter than 32 bytes with zeroes when forming signature bytes.

**Comment by m-kus** [comment]
Thanks!
