### ISSUE TITLE
No such file or directory: '~/.tezos-client/secret_keys'

### ISSUE THREAD

**Issue by samsondav** [baking-bad/pytezos#61]
It seems as if this library requires a secret keys file.

I want to run this on an AWS lambda, which cannot access the home directory. And state is not reliably persisted.

Is there some way of supplying the secret key as an argument or environment variable instead?

**Comment by m-kus** [comment]
Сould you please provide some code for the context? This feature (importing tezos-client keys) is optional, there are better ways to pass the secret key :)

**Comment by samphilipd** [comment]
I am trying to use it in the repl, following the quick start guide.

It says to run `pytezos.activate_account()` but it generates this error.

**Comment by m-kus** [comment]
If I’m not mistaken, we solved all the questions in dm, but for sum up here is how to pass private key via env variable:
```
>>> from pytezos import pytezos
>>> import os 

>>> os.environ['PRIVATE_KEY']
edsk2mVbss4Y9nMD1cUhwuCtmDYPeefnhWMEaQcLxSbp1Y4cdW66D8

>>> Key.from_encoded_key(os.environ['PRIVATE_KEY'])
<pytezos.crypto.Key object at 0x7f1b214b75c0>

Public key hash
tz1c62sqaTnVgfr3GG2Lw8W9jLE4HfHHBZwX

Helpers
.from_alias()
.from_encoded_key()
.from_faucet()
.from_mnemonic()
.from_public_point()
.from_secret_exponent()
.generate()
.is_secret
.public_key()
.public_key_hash()
.secret_key()
.sign()
.verify()
```
