### ISSUE TITLE
RpcError: 006-PsCARTHA.contract.balance_too_low

### ISSUE THREAD

**Issue by jpic** [baking-bad/pytezos#90]
Hi all,

What does this error look like to you ?

![2020-05-07-165409_599x161_scrot](https://user-images.githubusercontent.com/94636/81310185-11fb8300-9084-11ea-8d4b-a1db4004c100.png)

For me it seems to mean that it doesn't want to deploy a contract because the balance is of only 49 tz and it's asking for 1276 tz ... But that seems **a lot**, the same contract used to pass with just a few tz ...

Am I doing something wrong ? Does this make sense to you ?

Thank you

**Comment by m-kus** [comment]
Amount is in `utz`
Is that carthagenet/mainnet/sandboxnet?

**Comment by jpic** [comment]
Carthage.

Right ! Thanks for the heads up

**Comment by m-kus** [comment]
You can use @tezos_faucet_bot, which will always replenish your account

**Comment by jpic** [comment]
Thanks, I am using it to provision the other accounts !

Keep up the great work :tophat:
